# Generated by Django 2.1.8 on 2019-06-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('date_tmp', models.IntegerField(blank=True, null=True)),
                ('tokenized_doc', models.TextField(blank=True, null=True)),
                ('tokenized_title', models.TextField(blank=True, null=True)),
                ('cat_selected', models.TextField(blank=True, null=True)),
                ('topic', models.IntegerField(blank=True, null=True)),
                ('represent', models.IntegerField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
    ]
